######################################################################
# Automatically generated by qmake (2.01a) ?? 9? 25 18:20:24 2013
######################################################################

TEMPLATE = app
TARGET = DuySorter
MOC_DIR     = build/moc
OBJECTS_DIR = build/obj
RCC_DIR     = build/rcc
DEPENDPATH += . src/3rdparty src src/common
INCLUDEPATH += . src src/common src/3rdparty
CONFIG += qt debug_and_release warn_on thread
CONFIG += resources_big
QT += network widgets sql ftp
DEFINES += ENABLE_CAPTURE_SCREEN=1

CONFIG(release,debug|release){ 
        DEFINES += QT_NO_DEBUG_OUTPUT \
                   DEBUG_OUTPUT=0
}
else {
        DEFINES += DEBUG_OUTPUT=1
}

# ============ 目标架构自适应（VM 调试 x86_64 / 生产交叉编译 aarch64）============
# qmake 依据编译器目标架构自动选择 OpenCV / OpenSSL 的库路径
unix {
    contains(QT_ARCH, x86_64)|contains(QMAKE_TARGET.arch, x86_64) {
        message("qmake: target arch = x86_64 (host/VM debug)")
        # OpenCV 4.5.5（随项目分发）：上位机 x86_64 调试
        INCLUDEPATH += $$PWD/src/3rdparty/opencv/x86/include/opencv4 \
                       $$PWD/src/3rdparty/openssl/x86/include        \
                       $$PWD/src/3rdparty/unilog/x86/include

        LIBS += -L$$PWD/src/3rdparty/opencv/x86/lib  \
                -L$$PWD/src/3rdparty/openssl/x86/lib \
                -L$$PWD/src/3rdparty/unilog/x86/lib  \
                -lopencv_core -lopencv_imgproc -lopencv_imgcodecs \
                -lcrypto -lssl -lunilog
    } else {
        message("qmake: target arch = aarch64 (rk3566 production)")
        # OpenCV 4.5.5（随项目分发）：rk3566 aarch64 生产
        INCLUDEPATH += $$PWD/src/3rdparty/opencv/arm/include/opencv4 \
                       $$PWD/src/3rdparty/openssl/arm/include        \
                       $$PWD/src/3rdparty/unilog/arm/include

        LIBS += -L$$PWD/src/3rdparty/opencv/arm/lib  \
                -L$$PWD/src/3rdparty/openssl/arm/lib \
                -L$$PWD/src/3rdparty/unilog/arm/lib  \
                -lopencv_core -lopencv_imgproc -lopencv_imgcodecs \
                -lcrypto -lssl -lunilog
    }
}

# head file
HEADERS += $$PWD/src/*.h \
#第三方库
           $$PWD/src/3rdparty/qextserialport/*.h \
           $$PWD/src/3rdparty/libqrencode/*.h \
           $$PWD/src/3rdparty/qjson/*.h \
#自定义控件库
           $$PWD/src/common/libdccrypt/dccrypt.h \
           $$PWD/src/common/*.h \
           $$PWD/src/common/myqrcode/*.h \
#mono 目录（仅保留 CG 共用组件，已排除黑白专属文件）
           $$PWD/src/common/mono_shared/monoflow.h \
           $$PWD/src/common/mono_shared/feedctrl.h \
           $$PWD/src/common/mono_shared/feedercontrolthread.h \
           $$PWD/src/common/mono_shared/setfeed.h \
           $$PWD/src/common/mono_shared/autosetrs.h \
           $$PWD/src/common/mono_shared/copymajorparams.h \
           $$PWD/src/common/mono_shared/camerasignal/ejecttimesthread.h \
           $$PWD/src/common/mono_shared/camerasignal/ejecttimes.h \
           $$PWD/src/common/mono_shared/sortparams/paramsetalone.h \
           $$PWD/src/common/mono_shared/venderset/lampctrl.h \
           $$PWD/src/common/mono_shared/venderset/feederremotectrl.h \
           $$PWD/src/rgb/*.h \
           $$PWD/src/rgb/schemeparams/*.h \
    src/myicon.h \
    src/common/mycombobox.h \
    src/rgb/upgradefpga/upgradeprogramwidget.h \
    src/rgb/upgradefpga/upgradefpgawidget.h \
    src/rgb/upgradefpga/selectfiledialog.h \
    src/rgb/tickmodewidget.h \
    src/rgb/autoanalysiswidget.h
# source file
SOURCES += $$PWD/src/*.cpp \
#第三方库
           $$PWD/src/3rdparty/qextserialport/qextserialport.cpp \
           $$PWD/src/3rdparty/libqrencode/*.c \
           $$PWD/src/3rdparty/qjson/*.cpp \
#自定义控件库
           $$PWD/src/common/*.cpp \
           $$PWD/src/common/myqrcode/*.cpp \
#全局参数
           $$PWD/src/params/*.cpp \
#mono 目录（仅保留 CG 共用组件，已排除黑白专属文件）
           $$PWD/src/common/mono_shared/monoflow.cpp \
           $$PWD/src/common/mono_shared/feedctrl.cpp \
           $$PWD/src/common/mono_shared/feedercontrolthread.cpp \
           $$PWD/src/common/mono_shared/setfeed.cpp \
           $$PWD/src/common/mono_shared/autosetrs.cpp \
           $$PWD/src/common/mono_shared/copymajorparams.cpp \
           $$PWD/src/common/mono_shared/camerasignal/ejecttimesthread.cpp \
           $$PWD/src/common/mono_shared/camerasignal/ejecttimes.cpp \
           $$PWD/src/common/mono_shared/sortparams/paramsetalone.cpp \
           $$PWD/src/common/mono_shared/venderset/lampctrl.cpp \
           $$PWD/src/common/mono_shared/venderset/feederremotectrl.cpp \
           $$PWD/src/rgb/*.cpp \
           $$PWD/src/rgb/schemeparams/*.cpp \
    src/rgb/upgradefpga/upgradeprogramwidget.cpp \
    src/rgb/upgradefpga/upgradefpgawidget.cpp \
    src/rgb/upgradefpga/selectfiledialog.cpp

win32{
            DESTDIR = app

            SOURCES += $$PWD/src/3rdparty/qextserialport/qextserialport_win.cpp

            LIBS += -L$$PWD/src/3rdparty/openssl/lib_win32 -llibcrypto

            DEFINES += LCD_WIDTH=1024 \
                       LCD_HEIGHT=768 \
                       AI_MODE=0
}
unix{
            DESTDIR = $$[MYAPP_DIR]

            HEADERS += $$PWD/src/3rdparty/libusb/*.h \
                       $$PWD/src/common/myusb/*.h \
                       $$PWD/src/common/myeeprom/*.h

            SOURCES += $$PWD/src/3rdparty/qextserialport/qextserialport_unix.cpp \
                       $$PWD/src/3rdparty/libusb/*.c \
                       $$PWD/src/common/myusb/*.cpp \
                       $$PWD/src/common/myeeprom/*.c

            DEFINES += LCD_WIDTH=1024 \
                       LCD_HEIGHT=768 \
                       AI_MODE=0 \
                       PLATFORM=1
}

RESOURCES += res.qrc

TRANSLATIONS += i18n/zh-cn.ts \
                i18n/en.ts \
                i18n/es.ts \
                i18n/zh-tw.ts \
                i18n/vi.ts \
                i18n/fa.ts \
                i18n/ru.ts \
                i18n/tr.ts \
                i18n/fr.ts \
                i18n/pt.ts \
                i18n/ko.ts \
                i18n/th.ts \
                i18n/my.ts \
                i18n/ug.ts \
                i18n/ar.ts \
                i18n/bg.ts \
                i18n/sk.ts \
                i18n/bn.ts \
                i18n/id.ts \
                i18n/pl.ts

OTHER_FILES += $$PWD/qtmakeApp.sh \
               $$PWD/readme.txt

INSTALLS += target
target.path=/opt/app

FORMS += \
    aimodelset.ui
