#level:[TRACE | DEBUG | INFO | WARN | ERROR]
spdlog.level=INFO
#mode:[FILESIZE | DAYROLLING]
spdlog.mode=FILESIZE
spdlog.pattern=[%Y-%m-%d %H:%M:%S.%e] [thread %t %l] %v
spdlog.name=/opt/userdata/log/sorter.log
spdlog.file_num=3
#file_size: 200M
spdlog.file_size=209715200
#flush_on:[ON | OFF]
spdlog.flush_on=OFF